export interface Jugador{
    key?:string,
    nombre:string,
    j:number,
    g:number,
    e:number,
    p:number,
    c:number,
    f:number,
    elo:number,
    rol:string,
    email:string,
    equipo:boolean,
    titular:string,
}